# Generated by Django 5.0.7 on 2024-09-24 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logoimage',
            name='image',
            field=models.ImageField(upload_to='static/'),
        ),
    ]
